name: container
on: [workflow_dispatch]
jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: nginx
        steps:
            - name: whoami
              run: whoami
            - name: Python sleep demo
              uses: docker://python:3.9
              with:
                entrypoint: sh
                args: -c "python -V"
