name: Build & Publish Flask Docker Image

on:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  push-to-dockerhub-and-ghcr:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repository ---
      - uses: actions/checkout@v3

      # --- Docker Hub login ---
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # --- GHCR login ---
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # --- Extract Docker Metadata ---
      - name: Extract Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask
            ghcr.io/${{ github.repository_owner }}/flask
          tags: |
            type=ref,event=tag      # GitHub release tag
            type=sha                # fallback: commit SHA
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      # --- Build & Push Docker Images ---
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
