name: container
on: [workflow_dispatch]
jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: nginx
        steps:
            - name: whoami
              run: whoami

            - name: create a file
              run: echo "hello world" > myfile.txt

            - name: Python sleep demo
              uses: docker://python:3.9
              with:
                entrypoint: sh
                args: -c "python -V"
            
            - name: print contents of the file
              uses: docker://python:3.9  
              with:
                entrypoint: sh
                args: -c "cat myfile.txt"
            
            - name: git clone
              uses: actions/checkout@v3

            - name: run script
              uses: docker://python:3.9  
              with:
                entrypoint: sh
                args: -c "bash ./script.sh"