name: container
on: [workflow_dispatch]
jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: nginx
        steps:
            - name: whoami
              run: whoami
            - name: jenkinss
              uses: docker://jenkins/jenkins:2.516.2-lts-jdk21
              with:
                entrypoint: whoami