name: container
on: [workflow_dispatch]
jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: python:3.9
        steps:
            - name: whoami
              run: whoami
            - name: python version
              uses: docker://python:3.9
              with:
                entrypoint: /usr/bin/python3 -V